# === GENERAL ===
general:
  video_source: 'videos/video.mp4'
  frames_path: 'outputs/frames_output/frames.png'
  target_frame_save_path: 'outputs/frames_output/target_frame.png'
  resize_factor: 0.35 # '1' not to use
  strip_width: 130

# === SCAN ===
scan:
  verbose: True
  vizualize: True


# === INFERENCE ===
infer:
  delay: 30
  plot: True
  threshold: 1
  roi_width: 200
  down_scale: 1 # '1' not to use
  steps_per_rev: 200
  output_path: 'outputs/inference_outputs/infer_outputs.json'